FROM cpp-build-env:1.0 

WORKDIR /additions

RUN git clone -b $(curl -L https://grpc.io/release) https://github.com/grpc/grpc 

RUN cd grpc && git submodule update --init && ls .

RUN mkdir -p grpc/cmake/build && cd grpc/cmake && ls .. && \
cmake -DCMAKE_BUILD_TYPE=Release \
   -DgRPC_INSTALL=ON -DgRPC_BUILD_TESTS=OFF -DgRPC_SSL_PROVIDER=package .. && make install 


