// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: chesscom.proto

#include "chesscom.pb.h"
#include "chesscom.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace chesscom {

static const char* ChessCom_method_names[] = {
  "/chesscom.ChessCom/sendRequest",
};

std::unique_ptr< ChessCom::Stub> ChessCom::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ChessCom::Stub> stub(new ChessCom::Stub(channel));
  return stub;
}

ChessCom::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_sendRequest_(ChessCom_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status ChessCom::Stub::sendRequest(::grpc::ClientContext* context, const ::chesscom::MathRequest& request, ::chesscom::MathReply* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_sendRequest_, context, request, response);
}

void ChessCom::Stub::experimental_async::sendRequest(::grpc::ClientContext* context, const ::chesscom::MathRequest* request, ::chesscom::MathReply* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_sendRequest_, context, request, response, std::move(f));
}

void ChessCom::Stub::experimental_async::sendRequest(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::chesscom::MathReply* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_sendRequest_, context, request, response, std::move(f));
}

::grpc::ClientAsyncResponseReader< ::chesscom::MathReply>* ChessCom::Stub::AsyncsendRequestRaw(::grpc::ClientContext* context, const ::chesscom::MathRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::chesscom::MathReply>::Create(channel_.get(), cq, rpcmethod_sendRequest_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::chesscom::MathReply>* ChessCom::Stub::PrepareAsyncsendRequestRaw(::grpc::ClientContext* context, const ::chesscom::MathRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::chesscom::MathReply>::Create(channel_.get(), cq, rpcmethod_sendRequest_, context, request, false);
}

ChessCom::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ChessCom_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ChessCom::Service, ::chesscom::MathRequest, ::chesscom::MathReply>(
          std::mem_fn(&ChessCom::Service::sendRequest), this)));
}

ChessCom::Service::~Service() {
}

::grpc::Status ChessCom::Service::sendRequest(::grpc::ServerContext* context, const ::chesscom::MathRequest* request, ::chesscom::MathReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace chesscom

