// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chesscom.proto
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using grpc = global::Grpc.Core;

namespace ChessCom {
  /// <summary>
  /// Defines the service
  /// </summary>
  public static partial class ChessCom
  {
    static readonly string __ServiceName = "chesscom.ChessCom";

    static readonly grpc::Marshaller<global::ChessCom.MathRequest> __Marshaller_MathRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::ChessCom.MathRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::ChessCom.MathReply> __Marshaller_MathReply = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::ChessCom.MathReply.Parser.ParseFrom);

    static readonly grpc::Method<global::ChessCom.MathRequest, global::ChessCom.MathReply> __Method_sendRequest = new grpc::Method<global::ChessCom.MathRequest, global::ChessCom.MathReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "sendRequest",
        __Marshaller_MathRequest,
        __Marshaller_MathReply);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::ChessCom.ChesscomReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of ChessCom</summary>
    public abstract partial class ChessComBase
    {
      /// <summary>
      /// Function invoked to send the request
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      public virtual global::System.Threading.Tasks.Task<global::ChessCom.MathReply> sendRequest(global::ChessCom.MathRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for ChessCom</summary>
    public partial class ChessComClient : grpc::ClientBase<ChessComClient>
    {
      /// <summary>Creates a new client for ChessCom</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public ChessComClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for ChessCom that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public ChessComClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected ChessComClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected ChessComClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      /// Function invoked to send the request
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::ChessCom.MathReply sendRequest(global::ChessCom.MathRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return sendRequest(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Function invoked to send the request
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::ChessCom.MathReply sendRequest(global::ChessCom.MathRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_sendRequest, null, options, request);
      }
      /// <summary>
      /// Function invoked to send the request
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::ChessCom.MathReply> sendRequestAsync(global::ChessCom.MathRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return sendRequestAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Function invoked to send the request
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::ChessCom.MathReply> sendRequestAsync(global::ChessCom.MathRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_sendRequest, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override ChessComClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new ChessComClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(ChessComBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_sendRequest, serviceImpl.sendRequest).Build();
    }

  }
}
#endregion
